general:
  # MissAlignment iteratively trains models and realigns the tilt-series
  training_directory: /data/set/  # path to directory for writing iteration output
  apply_ctf: True                 # set to True if CTF estimates are available in .xml
  iteration_settings:             # defines all iterations to run (length determines number of iterations)
    # alignment modes: "global" (single pass), "anchoring" (iterative), "spline" (coarse-to-fine)
    - { downsample: 2, alignment: spline }
    - { downsample: 2, alignment: spline }
    - { downsample: 1, alignment: global }
    - { downsample: 1, alignment: global }
    - { downsample: 1, alignment: global }
    - { downsample: 1, alignment: [3, 3, 40] }  # local refinement with a 3x3 image warping grid
  seed: 45132

# ====================================================================
# Don't touch the parameters below unless you know what you are doing!

model_training:
  # used to initialize model weights
  model_architecture: 'default'
  model_checkpoint: /path/to/model.ckpt
  loss_margin: 0.5
  learning_rate: 1.0e-3
  # Set to zero to disable weight decay (i.e. the AdamW optimizer)
  weight_decay: 1.0e-4
  max_epochs_per_iteration: 30  # absolute maximum of stopping
  warmup_steps: 500
  multistep_lr_scheduler:
    milestones: [5, 15]
    gamma: 0.5                  # multiply learning rate by this value at the milestone epochs

data_loading:
  batch_size: 32                  # these value have been used as defaults:
  patch_size: 96                  # batch size 32 | reconstruction size 128 ^ 3
  steps_per_epoch: 1000           # this defines the size of an epoch

# this configures the shift generation for the contrastive training of MissAlignment
# all parameters are in units of pixels, thus shifts become larger when downsampling
shift_generation:
  trajectory_probability: .5      # these make bananas and birds
  trajectory_max_shift: 10.0      # trajectories fall somewhere between +/- f
  jitter_probability: .5
  jitter_max_std: 2.0             # maximum standard deviation of a normal distribution
  outlier_probability: .5
  outlier_max_shift: 20.0         # outlier can maximally go to this value
  fracture_probability: .5
  fracture_max_shift: 30.0       # specific strong shifts for high tilt images up to this value

tilt_series_alignment:
  patch_size: 96      # same as training patch size
  patch_overlap: 0.1  # tolerated overlap between patches used for optimizing the alignment
  batch_size: 16      # amount of patches simultaneously reconstructed in memory -> the more the merrier
