general:
  # MissAlignment iteratively trains models and realigns the tilt-series
  # here you can continue training from a specific iteration
  start_at_iteration: 0
  seed: 45132

model_training:
  # used to initialize model weights
  model_architecture: 'default'
  model_checkpoint: /path/to/model.ckpt
  output_directory: /path/to/   # here model checkpoints are stored in lightning_log directories
  loss_margin: 0.5
  learning_rate: 1.0e-3
  # Set to zero to disable weight decay (i.e. the AdamW optimizer)
  weight_decay: 1.0e-4
  max_epochs_per_iteration: 30  # absolute maximum of stopping
  warmup_steps: 500
  multistep_lr_scheduler:
    milestones: [5, 15]
    gamma: 0.5                  # multiply learning rate by this value at the milestone epochs

data_module:
  training_directory: /data/set/  # path to dataset location
  batch_size: 32                  # these value have been used as defaults:
  patch_size: 96                  # batch size 32 | reconstruction size 128 ^ 3
  steps_per_epoch: 1000           # this defines the size of an epoch

# this configures the shift generation for the contrastive training of MissAlignment
# all parameters are in units of 10A (nm) as we assume to work with tilt-series sampled to 10A
shift_generation:
  trajectory_probability: .5      # these make bananas and birds
  trajectory_max_shift: 10.0      # (10 A) trajectories fall somewhere between +/- f
  jitter_probability: .5
  jitter_max_std: 2.0             # (10 A) maximum standard deviation of a normal distribution
  outlier_probability: .5
  outlier_max_shift: 20.0         # (10 A) outlier can maximally go to this value
  fracture_probability: .5
  fracture_max_shift: 30.0       # (10 A) specific strong shifts for high tilt images up to this value

tilt_series_alignment:
  patch_size: 96      # same as training patch size
  patch_overlap: 0.1  # tolerated overlap between patches used for optimizing the alignment
  batch_size: 16      # amount of patches simultaneously reconstructed in memory -> the more the merrier
  apply_ctf: True     # whether to apply ctf when optimizing the alignments
